name: Pylint
on:
  push:
    paths:
      - '**.py'
    branches:
      - main
      - dev

  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - dev

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        pip install -r requirements.txt
    - name: Lint package source with pylint
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pylint azure-function-timer-trigger-code --max-line-length=127 --disable=R0801
